name: Generate Snake Animation

on:
  schedule:
    # Roda a cada 12 horas (Cron)
    - cron: "0 */12 * * *" 
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # Gera o arquivo SVG da cobrinha
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: vinicius-de-almeida # SEU USUÁRIO AQUI
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark # Versão para temas escuros

      # Commita e envia os arquivos gerados para a branch "output"
      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
